Repository WildCodeSchool/lyon-js-sept2020-p3-vh-front-office, pull requests merged in 2020-12, with the labels that each got.

#2 Routes
  package-lock.json
  package.json
  src/components/About/AboutAnimators.js
  src/components/About/AboutMorgane.js
  src/components/App.js
  src/components/Basket/Basket.js
  src/components/Contact/Contact.js
  src/components/Contact/Faq.js
  src/components/Events/Eventdetails.js
  src/components/Events/Events.js
  src/components/Home/Footer.js
  src/components/Home/Home.js
  src/components/Home/NavBar.js
  src/components/LogIns/Login.js
  src/components/LogIns/Register.js
  src/components/Products/Products.js
  src/components/Reviews/Reviews.js
  src/components/Sponsors/Sponsors.js
  src/services/API.js
Labels: Ready for prod

#34 Footer
  package-lock.json
  package.json
  src/components/App.js
  src/components/Home/Footer.js
  src/components/Home/Footer.scss
  src/components/Home/NavBar.js
  src/components/Home/NavBar.scss
  src/components/MentionLegale/MentionLegale.js
  src/components/_variablesCSS.scss
  src/components/pictures/facebook.svg
  src/components/pictures/hypnose_vins_logo.jpg
  src/components/pictures/hypnose_vins_logo.png
  src/components/pictures/hypnose_vins_logo6.pdf
  src/components/pictures/hypnose_vins_logo_web.png
Labels: Ready for prod

#30 Welcome carrousel+ banner
  package-lock.json
  package.json
  src/components/Home/Banner.js
  src/components/Home/Banner.scss
  src/components/Home/Home.js
  src/components/Home/WelcomeCarousel.js
  src/components/Home/WelcomeCarrousel.scss
Labels: Conflicts

#29 FAQ done
  package-lock.json
  package.json
  src/components/Contact/Faq.css
  src/components/Contact/Faq.js
  src/components/Home/Banner.js
  src/components/Home/Home.js
  src/components/Home/WelcomeCarousel.js
Labels: Ready for prod

#35 Footer
  src/components/Home/Footer.js
  src/components/Home/Footer.scss
  src/components/pictures/hypnose_vins_logo_icone.png
Labels: Ready for prod

#36 Form inscription
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/Home/Home.js
  src/components/Home/Translation.js
  src/components/Home/Translation.scss
  src/components/LogIns/Register.css
  src/components/LogIns/Register.js
  src/components/LogIns/Register.scss
  src/i18n.js
  src/index.js
Labels: Ready for prod

#39 Formulaire login
  package-lock.json
  package.json
  src/components/Home/Home.js
  src/components/LogIns/Login.js
  src/components/LogIns/Login.scss
  src/logo.jpg
Labels: Ready for validation

#38 Contact
  package-lock.json
  package.json
  src/components/Contact/Contact.js
  src/components/Contact/Contact.scss
Labels: WIP

#42 bug fixed
  src/components/App.js
  src/components/App.scss
  src/components/Home/Footer.js
Labels: Ready for prod

#43 using now material ui for modal (bootstrap removed)
  package-lock.json
  package.json
  src/components/App.js
  src/components/Products/WineModal.js
  src/components/Products/WineModal.scss
  src/components/Products/Wines.js
  src/components/Products/Wines.scss
  src/components/bootstrap.css
  src/index.js
Labels: Ready for prod

#41 Presentation morgan
  package-lock.json
  package.json
  src/components/About/AboutMorgane.js
  src/components/About/AboutMorgane.scss
  src/components/Contact/Contact.js
  src/components/Products/WineModal.scss
  src/components/Products/Wines.scss
  src/components/bootstrap.css
Labels: Ready for prod

#45 Connected form contact with back end
  package-lock.json
  package.json
  src/components/App.js
  src/components/Contact/Contact.js
  src/components/LogIns/Register.js
  src/components/LogIns/Register.scss
Labels: Ready for validation

#47 Back end and front end connected
  package.json
  src/components/App.js
  src/components/Home/Home.js
  src/components/Home/Sponsors.js
  src/components/Home/Sponsors.scss
  src/contexts/sponsorContext.js
Labels: Ready for validation

#48 Footer
  package-lock.json
  package.json
  src/components/App.scss
  src/components/Home/Footer.js
  src/components/Home/Footer.scss
  src/components/Products/WineModal.js
Labels: Ready for prod

#49 Navbar
  src/components/App.js
  src/components/App.scss
  src/components/Home/Home.js
  src/components/Home/MenuNavBar.js
  src/components/Home/NavBar.js
  src/components/Home/NavBar.scss
  src/components/Home/Translation.scss
  src/components/pictures/basket.svg
  src/components/pictures/calendar.svg
  src/components/pictures/cross.png
  src/components/pictures/login.png
Labels: Ready for prod
