Repository WildCodeSchool/lyon-js-sept2020-p3-vh-front-office, pull requests merged in 2021-01, with the labels that each got.

#44 Working login
  .env.sample
  Dockerfile
  default.conf
  package-lock.json
  package.json
  src/components/App.js
  src/components/Contact/Contact.js
  src/components/Contact/Contact.scss
  src/components/Contexts/LoginContext.js
  src/components/Home/Sponsors.js
  src/components/LogIns/Login.js
  src/components/LogIns/Login.scss
  src/components/LogIns/Profile.js
  src/components/LogIns/Profile.scss
  src/components/LogIns/Register.css
  src/components/LogIns/Register.js
  src/components/LogIns/Register.scss
  src/components/Products/WineModal.js
  src/files/facebook.png
  src/files/instagram.png
  src/files/twitter.png
  src/services/API.js
Labels: Ready for validation

#54 Refacto formulaire de contact
  src/components/Contact/Contact.js
  src/components/Contact/Contact.scss
  src/components/Home/Footer.scss
Labels: Ready for validation

#56 Aboutanimators
  src/components/About/AboutAnimators.js
  src/components/About/AboutAnimators.scss
  src/components/Contact/Contact.js
  src/components/Home/Footer.scss
  src/components/LogIns/Login.js
  src/components/LogIns/Register.js
Labels: Ready for validation

#58 Mentions legales
  src/components/Contact/Contact.js
  src/components/MentionLegale/MentionLegale.js
  src/components/MentionLegale/MentionsLegale.scss
Labels: Ready for validation

#55 Front event
  package-lock.json
  package.json
  src/components/Events/Eventdetail.scss
  src/components/Events/Eventdetails.js
  src/components/Events/Events.js
  src/components/Events/Events.scss
Labels: Ready for prod

#61 Navbar
  src/components/Home/MenuNavBar.js
  src/components/Home/NavBar.js
  src/components/Home/NavBar.scss
  src/components/Home/Translation.js
  src/components/Home/Translation.scss
Labels: Ready for validation

#60 Content morgane - Changed css - Added some content
  package-lock.json
  src/components/About/AboutMorgane.js
  src/components/About/AboutMorgane.scss
Labels: Ready for validation

#63 Event list
  src/components/Events/Events.js
  src/components/Events/Events.scss
  src/components/Home/Footer.scss
Labels: Ready for validation

#69 fixed style conflict with contact page
  src/components/Home/NavBar.scss
Labels: Ready for validation

#71 fix SCSS pages mentions légales
  src/components/MentionLegale/MentionsLegale.scss
Labels: Ready for validation

#67 Map event
  package-lock.json
  src/components/App.js
  src/components/Events/Eventdetail.scss
  src/components/Events/Eventdetails.js
Labels: Ready for validation

#72 Share button done
  package-lock.json
  package.json
  src/components/Events/Events.js
  src/components/Events/Events.scss
Labels: Ready for validation

#51 Ratings page
  package-lock.json
  package.json
  src/components/Reviews/Reviews.css
  src/components/Reviews/Reviews.js
Labels: Ready for prod

#75 Browser title
  package-lock.json
  package.json
  src/components/About/AboutAnimators.js
  src/components/About/AboutMorgane.js
  src/components/App.js
  src/components/Contact/Contact.js
  src/components/Contact/Faq.js
  src/components/Events/Eventdetails.js
  src/components/Events/Events.js
  src/components/LogIns/Login.js
  src/components/LogIns/Register.js
  src/components/MentionLegale/MentionLegale.js
  src/components/Products/Products.js
  src/components/Reviews/Reviews.js
Labels: Ready for validation

#57 Mise en place du panier
  package-lock.json
  package.json
  src/components/App.js
  src/components/Basket/Basket.js
  src/components/Basket/Basket.scss
  src/components/Basket/Disclaimer.js
  src/components/Basket/Disclaimer.scss
  src/components/Basket/OrderConfirmation.js
  src/components/Basket/OrderConfirmation.scss
  src/components/Contact/Contact.js
  src/components/Contexts/BasketContext.js
  src/components/Contexts/LoginContext.js
  src/components/Events/Eventdetail.scss
  src/components/Events/Eventdetails.js
  src/components/Events/Events.scss
  src/components/Home/NavBar.js
  src/components/Home/NavBar.scss
  src/components/LogIns/Profile.js
  src/services/API.js
  src/services/useLocalStorage.js
Labels: Ready for validation

#77 Reviews home page
  package-lock.json
  package.json
  src/components/Home/Home.js
  src/components/Home/Review.js
  src/components/Home/Review.scss
  src/components/Home/WelcomeCarrousel.scss
Labels: Ready for validation

#76 Calendar
  package-lock.json
  package.json
  src/components/Events/Calendar.scss
  src/components/Events/Eventdetail.scss
  src/components/Events/Events.js
  src/components/Events/Events.scss
Labels: Ready for validation

#70 Récupération de la FAQ depuis le back-end
  src/components/Contact/Faq.js
  src/components/Home/WelcomeCarousel.js
Labels: Ready for validation

#81 Nettoyage du style + ajout d'un loader + refonte de la home page
  package-lock.json
  package.json
  src/components/About/AboutMorgane.scss
  src/components/App.js
  src/components/Basket/Basket.scss
  src/components/Basket/Disclaimer.scss
  src/components/Basket/OrderConfirmation.scss
  src/components/Contact/Contact.scss
  src/components/Contact/Faq.css
  src/components/Contact/Faq.js
  src/components/Contact/Faq.scss
  src/components/Events/Calendar.scss
  src/components/Events/Eventdetail.scss
  src/components/Events/Eventdetails.js
  src/components/Events/Events.js
  src/components/Events/Events.scss
  src/components/Home/Banner.js
  src/components/Home/Banner.scss
  src/components/Home/Footer.js
  src/components/Home/Footer.scss
  src/components/Home/Home.js
  src/components/Home/NavBar.scss
  src/components/Home/Review.js
  src/components/Home/Review.scss
  src/components/Home/Sponsors.js
  src/components/Home/Sponsors.scss
  src/components/Home/Translation.js
  src/components/Home/Translation.scss
  src/components/Home/WelcomeCarousel.js
  src/components/Home/WelcomeCarrousel.scss
  src/components/LogIns/Login.js
  src/components/LogIns/Login.scss
  src/components/LogIns/Profile.scss
  src/components/LogIns/Register.scss
  src/components/MentionLegale/MentionsLegale.scss
  src/components/Products/WineModal.scss
  src/components/Products/Wines.scss
  src/components/Reviews/Reviews.css
  src/components/Reviews/Reviews.js
  src/components/Reviews/Reviews.scss
  src/components/Sponsors/Sponsors.js
  src/components/Sponsors/Sponsors.scss
  src/index.css
  src/index.js
  src/services/Loader.js
Labels: Ready for validation

#79 Design morgane
  src/components/About/AboutMorgane.js
  src/components/About/AboutMorgane.scss
Labels: Ready for validation

#83 Traduction
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/About/AboutAnimators.js
  src/components/About/AboutMorgane.js
  src/components/Basket/Basket.js
  src/components/Contact/Contact.js
  src/components/Contact/Faq.js
  src/components/Events/Eventdetails.js
  src/components/Events/Events.js
  src/components/Home/Banner.js
  src/components/Home/Footer.js
  src/components/Home/MenuNavBar.js
  src/components/Home/NavBar.js
  src/components/Home/Review.js
  src/components/LogIns/Login.js
  src/components/LogIns/Register.js
  src/components/MentionLegale/MentionLegale.js
  src/components/Products/WineModal.js
  src/components/Products/Wines.js
  src/components/Reviews/Reviews.js
  src/components/Sponsors/Sponsors.js
Labels: Ready for validation

#85 Events stylle
  src/components/Events/Events.js
  src/components/Events/Events.scss
Labels: Ready for validation

#84 incrémentation du panier lors des réservations
  src/components/About/AboutAnimators.js
  src/components/About/AboutAnimators.scss
  src/components/Contact/Faq.scss
  src/components/Home/Footer.js
  src/components/Home/Footer.scss
  src/components/Home/NavBar.js
  src/components/Home/NavBar.scss
  src/components/MentionLegale/MentionsLegale.scss
Labels: Ready for validation

#88 Modify calendar
  package-lock.json
  package.json
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/Events/Eventdetails.js
  src/components/Events/Events.js
  src/components/Events/Events.scss
Labels: Ready for validation

#89 Scrollbar
  package-lock.json
  package.json
  src/components/App.js
  src/components/Home/ScrollButton.js
  src/components/Home/ScrollButton.scss
Labels: Ready for validation

#86 event details scss done
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/Events/Eventdetail.scss
  src/components/Events/Eventdetails.js
  src/components/Home/Banner.js
  src/components/Home/Banner.scss
  src/components/Home/WelcomeCarrousel.scss
  src/components/_variablesCSS.scss
Labels: Ready for validation

#90 Home style
  src/components/Home/Banner.scss
  src/components/Home/Home.js
  src/components/Home/Reservation.js
  src/components/Home/Reservation.scss
  src/components/Home/Review.scss
  src/components/Sponsors/Sponsors.scss
Labels: Ready for validation

#78 User account
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/App.js
  src/components/Home/NavBar.js
  src/components/Home/NavBar.scss
  src/components/LogIns/Profile.js
  src/components/LogIns/Profile.scss
  src/components/LogIns/ProfileEvents.js
  src/components/LogIns/ProfileInformation.js
  src/components/LogIns/ReviewModal.js
Labels: Ready for validation

#91 Footer
  public/index.html
  src/components/App.scss
  src/components/Home/Footer.js
  src/components/Home/Footer.scss
Labels: Ready for validation

#92 Titles imglinks
  public/locales/fr/translation.json
  src/components/About/AboutAnimators.js
  src/components/About/AboutAnimators.scss
  src/components/About/AboutMorgane.js
  src/components/About/AboutMorgane.scss
  src/components/Basket/Basket.js
  src/components/Basket/Basket.scss
  src/components/Basket/Disclaimer.js
  src/components/Basket/Disclaimer.scss
  src/components/Basket/OrderConfirmation.js
  src/components/Basket/OrderConfirmation.scss
  src/components/Contact/Contact.js
  src/components/Contact/Contact.scss
  src/components/Contact/Faq.js
  src/components/Contact/Faq.scss
  src/components/Events/Eventdetail.scss
  src/components/Events/Events.js
  src/components/Events/Events.scss
  src/components/Home/Banner.scss
  src/components/Home/Footer.js
  src/components/Home/WelcomeCarousel.js
  src/components/LogIns/Login.js
  src/components/LogIns/Login.scss
  src/components/LogIns/Register.js
  src/components/LogIns/Register.scss
  src/components/MentionLegale/MentionLegale.js
  src/components/MentionLegale/MentionsLegale.scss
  src/components/Products/WineModal.js
  src/components/Products/Wines.js
  src/components/Products/Wines.scss
Labels: Ready for validation

#94 Redesign of Reviews
  src/components/App.js
  src/components/Reviews/Reviews.js
  src/components/Reviews/Reviews.scss
Labels: Ready for validation

#93 Traduction
  public/locales/en/translation.json
  public/locales/fr/translation.json
  src/components/About/AboutAnimators.js
  src/components/About/AboutMorgane.js
  src/components/Basket/Basket.js
  src/components/Basket/Disclaimer.js
  src/components/Basket/OrderConfirmation.js
  src/components/Events/Events.js
  src/components/Events/Events.scss
  src/components/Home/Footer.js
  src/components/Home/NavBar.js
  src/components/Home/Reservation.js
  src/components/Home/Review.js
  src/components/Home/WelcomeCarousel.js
  src/components/Products/Products.js
  src/components/Products/Wines.js
  src/components/Sponsors/Sponsors.js
Labels: WIP

#95 Navbar
  src/components/Home/NavBar.js
  src/components/Home/NavBar.scss
Labels: Ready for validation
